/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by electron-ipc-generate.
 * Any manual changes will be overwritten on next generation.
 */

/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck

import { useState, useCallback, useEffect } from 'react'


import { InvokeContracts } from "../main/ipc-api"

/**
 * React hook for invoke operations with automatic state management
 * @param channel - The IPC channel name
 * @returns Object with data, loading, error states and invoke function
 */
export function useInvokeInvokeContracts<K extends keyof InvokeContracts>(channel: K) {
  const [data, setData] = useState<InvokeContracts[K]["response"] | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<Error | null>(null)

  const invoke = useCallback(async (request: InvokeContracts[K]["request"]) => {
    setLoading(true)
    setError(null)
    try {
      const methodName = `invoke${channel}` as keyof typeof window.api
      const result = await (window.api[methodName] as any)(request)
      setData(result)
      return result
    } catch (err) {
      const error = err instanceof Error ? err : new Error(String(err))
      setError(error)
      throw error
    } finally {
      setLoading(false)
    }
  }, [channel])

  return { data, loading, error, invoke }
}


import { EventContracts } from "../main/ipc-api"

/**
 * React hook for event operations
 * @param channel - The IPC channel name
 * @returns Object with send function
 */
export function useEventEventContracts<K extends keyof EventContracts>(channel: K) {
  const send = useCallback((request: EventContracts[K]["request"]) => {
    const methodName = `send${channel}` as keyof typeof window.api
    ;(window.api[methodName] as any)(request)
  }, [channel])

  return { send }
}


import { BroadcastContracts } from "../main/ipc-api"

/**
 * React hook for broadcast operations with automatic subscription management
 * @param channel - The IPC channel name
 * @returns Object with data, subscribe, and unsubscribe functions
 */
export function useBroadcastBroadcastContracts<K extends keyof BroadcastContracts>(channel: K) {
  const [data, setData] = useState<BroadcastContracts[K]["payload"] | null>(null)

  const subscribe = useCallback((callback?: (payload: BroadcastContracts[K]["payload"]) => void) => {
    const handler = (data: any) => {
      setData(data)
      callback?.(data)
    }
    const onMethodName = `on${channel}` as keyof typeof window.api
    return (window.api[onMethodName] as any)(handler)
  }, [channel])

  return { data, subscribe }
}
