import { useEffect, useState } from 'react'

export function App() {
  const [a, setA] = useState('1')
  const [b, setB] = useState('2')
  const [sum, setSum] = useState<number | null>(null)
  const [error, setError] = useState('')
  const [aboutMessage, setAboutMessage] = useState('Waiting for About broadcast...')

  useEffect(() => {
    const unsubscribe = window.api.onAbout(() => {
      setAboutMessage(`About clicked at ${new Date().toLocaleTimeString()}`)
    })

    return unsubscribe
  }, [])

  const onAdd = async () => {
    setError('')
    const aNumber = Number(a)
    const bNumber = Number(b)

    if (Number.isNaN(aNumber) || Number.isNaN(bNumber)) {
      setError('Please enter valid numbers.')
      return
    }

    try {
      const result = await window.api.invokeAdd({ a: aNumber, b: bNumber })
      setSum(result)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Add failed')
    }
  }

  const onQuit = () => {
    window.api.sendQuit()
  }

  return (
    <div className="container">
      <header className="header">
        <h1>__PRODUCT_NAME__</h1>
        <p className="subtitle">Type-safe IPC contracts generated by @number10/electron-ipc</p>
      </header>

      <section className="section">
        <h2 className="section-title">🔄 Invoke</h2>
        <div className="demo-grid">
          <div className="demo-card invoke">
            <h3 className="demo-title">Add</h3>
            <p className="demo-description">Request-response invoke contract.</p>
            <div className="demo-controls">
              <input
                type="number"
                value={a}
                onChange={(event) => {
                  setA(event.target.value)
                }}
                aria-label="Number A"
              />
              <input
                type="number"
                value={b}
                onChange={(event) => {
                  setB(event.target.value)
                }}
                aria-label="Number B"
              />
              <button className="primary" onClick={onAdd}>
                Add
              </button>
            </div>
            {sum !== null && <div className="demo-result">Result: {sum}</div>}
            {error && <div className="demo-error">{error}</div>}
          </div>
        </div>
      </section>

      <section className="section">
        <h2 className="section-title">📤 Event</h2>
        <div className="demo-grid">
          <div className="demo-card event">
            <h3 className="demo-title">Quit</h3>
            <p className="demo-description">Fire-and-forget event to close the app.</p>
            <div className="demo-controls">
              <button onClick={onQuit}>Quit App</button>
            </div>
          </div>
        </div>
      </section>

      <section className="section">
        <h2 className="section-title">📡 Broadcast</h2>
        <div className="demo-grid">
          <div className="demo-card broadcast">
            <h3 className="demo-title">About</h3>
            <p className="demo-description">Triggered by the app menu.</p>
            <div className="demo-result">{aboutMessage}</div>
          </div>
        </div>
      </section>

      <footer className="footer">
        <p>
          Open the menu to trigger <code>About</code>, or click <code>Quit</code> to exit.
        </p>
      </footer>
    </div>
  )
}
