/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by electron-ipc-generate.
 * Any manual changes will be overwritten on next generation.
 */

/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck

import { BrowserWindow } from 'electron'
import { BroadcastContracts } from './ipc-api'

/**
 * Main process broadcast API for sending messages to renderer
 */
export const mainBroadcast = {
  Ping: (mainWindow: BrowserWindow, payload: BroadcastContracts['Ping']['payload']): void => {
    mainWindow.webContents.send('Ping', payload)
  },
}
